### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by alexanderzeillinger** [shadowmite/TouchPlusCMDR#1]
Hey Matthew,

first thanks for your efforts on taking matters into your own hands - I really appreciate that.

So in my understanding the implementation would have 2 steps:
A) Reliably identify and track fingers / fingertips / (fingernails?)
B) Based on above tracking recognize movements/actions

So obviously this is at the very beginning of step A now. At this step the following order would make sense for me:
1) Separate/extract hand(s) from background (tabletop)
2) Distinguish fingers
3) Recognize fingertips/fingernails

Can you share some information on which data is available to work with? Also, please comment the code as detailed as possible, so everyone can at least read what you are trying to do with various filters and techniques, thanks!

For anyone else interested, here's the list of filters available with the AForge library:
http://www.aforgenet.com/framework/docs/html/cdf93487-0659-e371-fed9-3b216efb6954.htm

**Comment by shadowmite** [comment]
Yep, I'll have to work on commenting it up a little more once I get something working well enough to justify it. As it is, I've gone through an amazing number of iterations just trying to get close to something that will work. Essentially looking for routines with some possibility of doing what we want. What I've got now is getting better, but it seems to false a little. I might have to resort to fiddling with the filters some more. 

Essentially I'm still trying to perfectly isolate the hand and/or fingers. Looking at the data I'm getting, there is currently no way to determine z-depth with any accuracy. Might need to look into the ETron chipsets ZDTable which I see is a function in the dll file. That _could_ be my answer to that.

**Comment by alexanderzeillinger** [comment]
With the Ractiv SDK suddenly being released, what can you do with that?

**Comment by shadowmite** [comment]
Unfortunately, not much. That SDK only does what I already figured out how to do myself. They removed anything related to the 3D modeling or blob detection. Granted they do have the function prototypes for the ETron library functions, it's debatable without knowing how they are supposed to work what to do with them. Especially since ETron is sticking to their statement that Ractiv did not follow the reference specification properly and their will most likely be problems. :(

I just need to tinker with object detection until I get something that seems workable. 

It is interesting however that Ractiv chooses to release this only AFTER a backer manages to work out how to do the same thing anyway.
